### ISSUE TITLE
Kplex stopping when DNS lookup failed

### ISSUE THREAD

**Issue by tjswe** [stripydog/kplex#49] opened 2020-12-01 10:15 UTC
An issue last night where kplex stopped because of what seems a DNS lookup issue. Had to do a restart of the service. It has been running fine for at least 3-4 months so this came sort of out of the blue.

Running version 1.4-17-g6e1f698 (which was an experimental branch with kplex doing new lookups if disconnected if i remember correctly)

Dec 01 01:33:18 host1 kplex[443]: Lookup failed for host ais.domainname.com/service 6344: Temporary failure in name resolution
Dec 01 01:33:18 host1 systemd[1]: kplex.service: Main process exited, code=killed, status=11/SEGV
Dec 01 01:33:18 host1 systemd[1]: kplex.service: Failed with result 'signal'.

The service stopping could perhaps be solved with a Restart=on-failure or Restart=always in the service file, but failing in the first place is perhaps something that should not occur just because of a failed DNS lookup.

**Comment by stripydog** [comment] 2020-12-01 19:49
Thanks! That looks like a SEGV which is disturbing and definitely a bug: thanks for finding it: I'll look into it

**Comment by stripydog** [comment] 2020-12-03 17:47
Thanks again for reporting that: it was a bad bit of quality control on my part.  I've pushed a change to the develop branch which should fix this.  Please give it a go and let me know if it works.  And thanks again!

**Comment by tjswe** [comment] 2020-12-04 13:43
No problem! Glad to be able to contribute!

Will update. Since this was the first and only issue in 4 months there will perhaps not be a quick feedback on the fix :)

**Comment by stripydog** [comment] 2020-12-04 14:47
Thanks.  I recreated the problem using packet filtering to simulate a dropped network connection and confirmed that the fix resolved things.  The downside to the new behaviour is that if name resolution is not possible when kplex reconnects a persistent interface, it will wait until DNS *does* become available before reconnecting but this does at least now work as intended rather than segmentation faulting.  I'll leave this open for a couple more days then close it.  If you see the problem again do please re-open or open another one.

**Closed as completed** 2020-12-22 18:54 UTC
